### ISSUE TITLE
Compatibility issue with Essentials Mod

### ISSUE THREAD

**Issue by Dootama** [Wolfsurge/AdvancedAdvancements#1]
Your mod causes the player model to bug out in menus for the essential mod, it looks all flashy.

**Comment by surge541** [comment]
Will have a look at it, thanks.

**Comment by surge541** [comment]
I've just released [version 1.11](https://modrinth.com/mod/advanced-advancements/version/1.11) which should hopefully fix the issue. Feel free to re-open this issue if any more conflicts arise.
